server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///xdb

redis:
  port: 6379
  host: localhost

## 用户生成jwt字符串的secretKey
jwt:
  secretKey: c239

logging:
  level:
    com.example.springbootDemo: debug

